[build]
base    = "client"
command = "npm run build"
publish = "dist"

[[edge_functions]]
function = "seo-preview"
path = "/blog/*"

[[redirects]]
from   = "/sitemap.xml"
to     = "https://dnarai-travels.onrender.com/sitemap.xml"
status = 200
force  = true

[[redirects]]
from   = "/robots.txt"
to     = "https://dnarai-travels.onrender.com/robots.txt"
status = 200
force  = true

[[redirects]]
from   = "/*"
to     = "/index.html"
status = 200